name: gsdatabase
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  dartx: ^1.2.0
  rxdart: ^0.27.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.3.0
  build_runner: ^2.4.7
